#!/bin/bash

source variables

if [ $# == 1 ]; then
        mkdir $1
        echo "Successfully created the folder at the current path $1"
  else
      if [ $# == 2 ]; then
            cd $1
            mkdir $2
            cd "${INSTALLDIR}"
            echo "$INSTALLDIR"
            echo "Successfully created the folder $2 at path $1"
            
        else
            
            echo "+------------------------------------------------------------------------------------+"
            echo "|Syntax error: This command only accepts 1 or 2 arguments, $# arguments were provided|"
            echo "|Correct Syntax: 'new <Directory> <Folder name>                                      |"
            echo "+------------------------------------------------------------------------------------+"
            afplay ./storage/assets/error.mov
            exit 1
        fi
  fi