#!/bin/bash

source variables

if [ $1 == "create" ]; then
    if [ -f "~/Documents/GX-Dev-Repos/$2" ]; then
        echo "This Git repository already exists, re-initilizing repository..."
        cd ~/Documents/GX-Dev-Repos/$2
        git init
    else 
        if [ $# == 2 ]; then
            cd ~/Documents
            mkdir GX-Dev-Repos
            cd ./GX-Dev-Repos
            mkdir $2
            cd ./$2
            git init
            echo ""
            echo "+----------------------------Created New Git Repository------------------------------+"
            echo "|A new git repo has been created in Documents/GX-Dev-Repos/                          |"
            echo "|                                                                                    |"
            echo "+------------------------------------------------------------------------------------+"
            echo ""
         else        
            echo ""
            echo "+------------------------------------------------------------------------------------+"
            echo "|Syntax error: This command only accepts 2 arguments, $# arguments were provided     |"
            echo "|Correct Syntax: 'new <Directory> <Folder name>                                      |"
            echo "+------------------------------------------------------------------------------------+"
            echo ""
            afplay ./storage/assets/error.mov
            exit 1
         fi
    fi
fi
