#!/bin/bash

echo "setting up your GXS-Dev environment"

brew install git
brew install zenity

echo ""
echo "+------------------------------Installation Wizard-----------------------------------+"
echo "| Your GXS Developer environment has been set up sucessfully, run 'gxsdev help for   |"
echo "| more info                                                                          |"
echo "+------------------------------------------------------------------------------------+"
echo ""

source test
