#!/bin/bash

VERSIONID="0.0.7"
RED="\033[0;31m"
REDBG="\e[1;41m"
BLUE="\033[0;34m"
BLUEBG="\e[1;44m"
WHITEBG="\e[1;47m"

# No Color
NC="\033[0m"

FILECT=$(find . -maxdepth 1 -type f | wc -l)

LOG="./storage/main.log"

echo "Set all vars" >> ${LOG}