#!/bin/bash

source variables


if [[ $# == 2 ]]; then
      echo "$2" > $1
      echo "Successfully wrote contents to the file $1"   
     else
      echo "+------------------------------------------------------------------------------------+"
      echo "|Syntax error: This command only accepts 2 or 3 arguments, $# arguments were provided |"
      echo "|Correct Syntax: 'write <Path to file> <Contents to write>'                          |"
      echo "+------------------------------------------------------------------------------------+"
      afplay ./storage/assets/error.mov
      exit 1
fi
  